
Parameters:
  ClusterName:
    Type: String

Resources:

  SharedInstanceCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
        Name: !Sub "rosa-rds-shared-instance-credentials-${ClusterName}"
        Description: 'Secret with dynamically generated password.'
        GenerateSecretString:
            RequireEachIncludedType: True
            SecretStringTemplate: '{}'
#            SecretStringTemplate: '{"username": "rds-shared-instance-master-user"}'
            GenerateStringKey: 'password'
            PasswordLength: 25
            ExcludePunctuation: True
