AWSTemplateFormatVersion: '2010-09-09'


Parameters:
     OidcProvider:
         Type: String
     ClusterName:
         Type: String

Resources:
    CloudwatchLoggingStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            Parameters:
               OidcProvider: !Ref OidcProvider
               ClusterName: !Ref ClusterName
            TemplateURL: https://raw.githubusercontent.com/open-sudo/rosa-idp/main/cloudformation/rosa-cloudwatch-logging-role.yaml

    CloudwatchMetricsStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            Parameters:
               OidcProvider: !Ref OidcProvider
               ClusterName: !Ref ClusterName
            TemplateURL: https://raw.githubusercontent.com/open-sudo/rosa-idp/main/cloudformation/rosa-cloudwatch-metrics-credentials.yaml
            
    ExternalSecretStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            Parameters:
               OidcProvider: !Ref OidcProvider
               ClusterName: !Ref ClusterName
            TemplateURL: https://raw.githubusercontent.com/open-sudo/rosa-idp/main/cloudformation/rosa-iam-external-secrets-role.yaml
            
    ElasticContainerRegistryStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: https://raw.githubusercontent.com/open-sudo/rosa-idp/main/cloudformation/rosa-ecr.yaml
            
 
