
Parameters:
  ClusterName:
    Type: String


Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties: 
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      Serial: 1
      Status: Active
      UserName: !Ref IamUser
  AccessKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Sub "These are the credentials for the IAM User ${IamUser}"
      Name: !Sub "rosa-rds-inventory-credentials-${ClusterName}"
      SecretString: 
               !Sub
                 - '{"AWS_ACCESS_KEY_ID":  "${AccessKey}","AWS_SECRET_ACCESS_KEY": "${SecretKey}", "AWS_REGION" : "${Region}"}'
                 - AccessKey: !Ref AccessKey
                   SecretKey:  !GetAtt AccessKey.SecretAccessKey
                   Region: !Ref AWS::Region




