AWSTemplateFormatVersion: "2010-09-09"


Parameters:
  ClusterName:
    Type: String
  SubnetId:
    Type: String
  SecurityGroupName:
    Type: String
Resources:
  InboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroupName
      IpProtocol: tcp
      FromPort: 2049
      ToPort: 2049
      SourceSecurityGroupId: !Ref SecurityGroupName

  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      BackupPolicy:
        Status: ENABLED
  EFSMountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: EFSFileSystem
      SubnetId: !Ref SubnetId
      SecurityGroups:
      - !Ref SecurityGroupName
Outputs:
  ElasticFileSystem:
    Description: Elastic file system.
    Value:
      Ref: EFSFileSystem


