AWSTemplateFormatVersion: "2010-09-09"


Parameters:
  ClusterName:
    Type: String



Resources:
  RosaECRPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowROSAReadAccessToECR
            Effect: Allow
            Action:
              -  'ecr:GetAuthorizationToken'
              -  'ecr:BatchCheckLayerAvailability'
              -  'ecr:GetDownloadUrlForLayer'
              -  'ecr:GetRepositoryPolicy'
              -  'ecr:DescribeRepositories'
              -  'ecr:ListImages'
              -  'ecr:DescribeImages'
              -  'ecr:BatchGetImage'
              -  'ecr:GetLifecyclePolicy'
              -  'ecr:GetLifecyclePolicyPreview'
              -  'ecr:ListTagsForResource'
              -  'ecr:DescribeImageScanFindings'
            Resource: '*'
      Roles: 
         - "ManagedOpenShift-Worker-Role"

         
      

