Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties: 
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      Serial: 1
      Status: Active
      UserName: !Ref IamUser
  AccessKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Sub "These are the credentials for the IAM User ${IamUser}"
      Name: ack-rds-user-secrets
      SecretString: 
               !Sub
                 - '{"AWS_ACCESS_KEY_ID":  "${AccessKey}","AWS_SECRET_ACCESS_KEY": "${SecretKey}"}'
                 - AccessKey: !Ref AccessKey
                   SecretKey:  !GetAtt AccessKey.SecretAccessKey




