AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SubnetId:
    Type: String
  VPC:
    Type: String
  SecurityGroupName:
    Type: String
Resources:
  EFSSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "security group for the prod EFS"
            GroupName: "test-EFS-SG"
            VpcId: !Ref VPC
            SecurityGroupIngress: 
              - CidrIp: 0.0.0.0/0
                FromPort: 2049
                IpProtocol: "tcp"
                ToPort: 2049

  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      BackupPolicy:
        Status: ENABLED
  EFSMountTargetAZ1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        Ref: EFSFileSystem
      SubnetId: !Ref SubnetId
      SecurityGroups:
      - !Ref SecurityGroupName
Outputs:
  ElasticFileSystem:
    Description: Elastic file system.
    Value:
      Ref: EFSFileSystem


