Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties: 
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      Serial: 1
      Status: Active
      UserName: !Ref IamUser
  AccessKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Sub "These are the credentials for the IAM User ${IamUser}"
      Name: rosa-rds-inventory-credentials
      SecretString: 
               !Sub
                 - 'AWS_ACCESS_KEY = ${AccessKey}
              
                   AWS_SECRET_KEY = ${SecretKey}

                   REGION = ${Region}'
                 - AccessKey: !Ref AccessKey
                   SecretKey:  !GetAtt AccessKey.SecretAccessKey
                   Region: !Ref AWS::Region




