
Parameters:
  ClusterName:
    Type: String


Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties: 
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties: 
      Serial: 1
      Status: Active
      UserName: !Ref IamUser
  AccessKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: !Sub "These are the credentials for the IAM User ${IamUser}"
      Name: rosa-cloudwatch-metrics-credentials
      SecretString: 
        Fn::Sub:
          - "{\"credentials\":\"${content}\"}"
          - content:
              Fn::Base64:
               !Sub
                 - '[AmazonCloudWatchAgent]
              
                   aws_access_key_id = ${AccessKey}
              
                   aws_secret_access_key = ${SecretKey}'
                 - AccessKey: !Ref AccessKey
                   SecretKey:  !GetAtt AccessKey.SecretAccessKey




