apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "7"

spec:
  provider:
    aws:
      service: SecretsManager
      region: __REGION__
      auth:
        jwt:
          serviceAccountRef:
              name: iam-external-secrets-sa
              namespace: external-secrets

