apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-external-secrets-sa
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: arn:aws:iam::__AWS_ACCOUNT_ID__:role/__CLUSTER_NAME__-RosaClusterSecrets
