apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  project: default
  source:
    repoURL: https://github.com/open-sudo/rosa-idp.git
    path: external-secrets
    targetVersion: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
