apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-operators
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    helm:
      releaseName: external-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openshift-operators
