apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  project: default
  source:
    chart: openshift-operators
    repoURL: https://charts.external-secrets.io
    targetRevision: v0.7.0
    helm:
      releaseName: external-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openshift-operators
