apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mta-operator
  namespace: mta
spec:
  channel: stable-v6.0
  installPlanApproval: Automatic
  name: mta-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  currentCSV: mta-operator.v6.0.0
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: mta-operator
spec:
  targetNamespaces: ['mta']

