
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
   operators.coreos.com/cluster-logging.openshift-logging: ""
  name: cluster-logging
  namespace: openshift-logging-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-credentials
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"

stringData:
  role_arn: "arn:aws:iam::__AWS_ACCOUNT_ID__:role/__CLUSTER_NAME__-RosaClusterWatchLogging"
---
apiVersion: "logging.openshift.io/v1"
kind: ClusterLogForwarder
metadata:
  name: cluster-log-forwarder
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "7"

spec:
  outputs:
    - name: cw
      type: cloudwatch
      cloudwatch:
        groupBy: namespaceName
        groupPrefix: rosa-{{ .Values.rosa.clusterName }}
        region: {{ .Values.rosa.region }}
      secret:
        name: cloudwatch-credentials
  pipelines:
     - name: to-cloudwatch
       inputRefs:
         - infrastructure
         - audit
         - application
       outputRefs:
         - cw
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: cluster-logging-instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  collection:
    logs:
       type: fluentd
  forwarder:
    fluentd: {}
  managementState: Managed

