---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-main-application
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: rosa.region
          value: "us-east-2"
        - name: rosa.clusterName
          value: "bombei"
        - name: aws.accountId
          value: "218444713402"
        - name: aws.cloudwatch.roleArn
          value: "arn:aws:iam::218444713402:role/bombei-RosaClusterWatch"
    repoURL: https://github.com/open-sudo/rosa-idp.git
    path: argocd-umbrella-application
    targetRevision: HEAD
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
