apiVersion: v1
kind: ServiceAccount
metadata:
  name: iam-external-secrets-rds-sa
  namespace: ack-system
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    eks.amazonaws.com/role-arn: arn:aws:iam::030492679077:role/milan-RosaRdsClusterSecrets
