apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudwatch-metrics
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/open-sudo/rosa-idp.git
    targetRevision: HEAD
    path: cloudwatch-metrics
    helm:
      values: |
        installCRDs: true
        rosa.region: __REGION__
        rosa.name: __CLUSTER_NAME__
        aws.cloudwatch.roleArn: "arn:aws:iam::__AWS_ACCOUNT_ID__:role/__CLUSTER_NAME__-RosaClusterWatchMetrics"

  destination:
    server: https://kubernetes.default.svc
    namespace: amazon-cloudwatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - Replace=true
    - ServerSideApply=true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy 
