apiVersion: dbaas.redhat.com/v1alpha1
kind: DBaaSInventory
metadata:
  labels:
    related-to: dbaas-operator
    type: dbaas-vendor-service
  name: rds-shared-inventory
  namespace: openshift-dbaas-operator
spec:
  credentialsRef:
    name: rosa-rds-inventory-credentials-{{ .Values.clusterName }}
  providerRef:
    name: rds-registration
